const BAD_REQUEST_ERROR = 400;
const PAGE_NOT_FOUND_ERROR = 404;
const ITERNAL_SERVER_ERROR = 500;
const OK_CODE = 200;
const BAD_REQUEST_MESSAGE = 'Данные не корректны';
const PAGE_NOT_FOUND_MESSAGE = 'Не найдены данные';
const ITERNAL_SERVER_MESSAGE = 'Произошла ошибка';

module.exports = {
  BAD_REQUEST_ERROR,
  PAGE_NOT_FOUND_ERROR,
  ITERNAL_SERVER_ERROR,
  BAD_REQUEST_MESSAGE,
  OK_CODE,
  PAGE_NOT_FOUND_MESSAGE,
  ITERNAL_SERVER_MESSAGE,
};
